
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
       62,   62,   65,   64,    1,   63,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,    2,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   46,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,    2,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   59,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

        0,   62,   62,   62,   62,   62,   62,   62,    4,   62,
       61,   62,   62,   62,   62,   62,   62,    9,   62,   13,
       62,   62,   62,   62,   62,    0,   58,   62,   62,    5,
       62,   62,   62,   62,   62,   62,   59,   62,   62,   62,
       62,   47,   62,   62,   62,   57,   62,   62,    8,   62,
        7,   62,   62,   57,   62,    0,    0,   62,   62,   62,
       57,   62,   62,   62,   12,   62,   62,   35,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,    0,
       58,   48,   62,   62,   62,    3,   62,   62,   62,   62,
       62,   62,   11,   62,   55,   62,   49,   62,   62,   26,

       62,   25,   62,   62,   62,   62,   62,    0,    0,   62,
       62,   60,   62,   36,   62,   62,   62,   12,    0,   62,
       41,   42,   62,   10,   62,   62,   27,   62,    6,   62,
       62,   37,    0,   62,   62,   62,   45,   62,   62,    0,
       62,   38,   51,   62,   11,   62,   29,   14,   55,   62,
       62,   62,   62,   62,   62,   62,   57,   62,    0,    0,
       62,   60,   62,   62,   62,   62,   62,   62,   30,    0,
       62,    5,   62,   62,   62,   62,   62,   62,   24,   62,
       42,   62,   15,   62,   23,   34,   52,    0,   62,   62,
       62,   62,   18,   62,   62,   62,   54,   31,   50,    0,

       48,   33,   62,   62,   62,   62,    0,   62,   62,   62,
       28,   19,   62,   56,   62,   62,   62,    0,   62,    0,
       62,   21,   62,   62,   17,   49,   62,   44,   22,   62,
        0,   62,   62,   62,   16,   62,   32,    0,   62,    0,
       62,   43,   62,    0,   62,   20,   62,    0,    0,   62,
       62,    0,   62,    0,    0,   62,    0,   62,    0,    0,
       62,    0,   62,   42,    0,   62,    0,   62,    0,   62,
        0,   62,    0,   62,    0,   39,    0,   40,   39,   40,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    8,    9,   10,

       11,   12,   13,   14,   15,    6,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[32] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2
    } ;

static const flex_int16_t yy_base[384] =
    {   0,
        0,    0,  746,  747,  747,  747,  740,  739,   27,   28,
       30,   29,   35,   54,   32,   34,   51,   57,   61,   62,
       73,   74,   80,   87,  101,   37,   76,  738,  737,  736,
       84,   63,   33,  735,   77,   94,   78,   96,   85,  104,
      102,   99,  113,  122,  123,  114,  131,  105,  134,  734,
      136,  139,  115,  142,  143,  146,  144,  147,  149,  151,
      150,  153,  154,  165,  159,  170,  166,  188,  171,  179,
      173,  176,  185,  181,  189,  192,  196,   40,  167,  197,
      202,  200,  208,  211,  210,  213,  215,  218,  219,  221,
      214,  222,  223,  226,  224,  225,  228,  231,  232,  229,

      238,  247,  248,  249,  251,  250,  259,  260,  733,  253,
      732,  256,  264,  265,  268,  269,  270,  252,  273,  731,
      277,  281,  282,  283,  286,  710,  287,  288,  290,  729,
      293,  295,  297,  308,  301,  309,  728,  312,  313,  296,
      318,  727,  319,  320,  321,  726,  336,  323,  725,  322,
      328,  329,  326,  333,  330,  722,  705,  350,  334,  337,
      340,  341,  353,  354,  356,  357,  365,  722,  360,  362,
      368,  369,  370,  379,  375,  377,  371,  388,  391,  712,
      720,  719,  392,  378,  395,  718,  393,  298,  396,  403,
      400,  405,  420,  407,  412,  415,  717,  416,  417,  716,

      418,  715,  428,  432,  435,  425,  436,  702,  692,  437,
      440,  439,  459,  712,  443,  447,  450,  711,  449,  451,
      710,  709,  461,  462,  463,  464,  708,  473,  707,  477,
      452,  706,  699,  468,  480,  481,  704,  413,  476,  485,
      492,  703,  702,  489,  701,  493,  700,  699,  698,  497,
      496,  485,  498,  503,  504,  508,  697,  511,  677,  689,
      512,  694,  515,  516,  517,  519,  520,  521,  693,  690,
      524,  528,  533,  531,  532,  535,  534,  538,  691,  536,
      691,  537,  689,  548,  688,  687,  686,  683,  549,  551,
      555,  557,  684,  560,  561,  562,  683,  682,  681,  674,

      747,  679,  564,  566,  563,  571,  660,  573,  574,  578,
      677,  676,  581,  675,  582,  583,  587,  658,  585,  655,
      588,  672,  586,  589,  671,  747,  593,  670,  669,  597,
      662,  598,  599,  600,  667,  602,  666,  650,  607,  658,
      604,  663,  609,  648,  610,  661,  615,  637,  645,  614,
      617,  638,  619,  649,  634,  626,  644,  621,  634,  641,
      625,  643,  629,  747,  641,  632,  626,  633,  625,  636,
      632,  637,  631,  638,  621,  639,  537,  500,  747,  747,
      747,  101,   69
    } ;

static const flex_int16_t yy_def[384] =
    {   0,
      381,    1,  381,  381,  381,  381,  382,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  382,  382,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      381,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  381,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  381,  381,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  381,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  381,  381,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  381,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  381,  383,  383,  383,  383,  383,  383,  381,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  381,  381,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  381,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      381,  383,  383,  383,  383,  383,  383,  381,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  381,

      381,  383,  383,  383,  383,  383,  381,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  381,  383,  381,
      383,  383,  383,  383,  383,  381,  383,  383,  383,  383,
      381,  383,  383,  383,  383,  383,  383,  381,  383,  381,
      383,  383,  383,  381,  383,  383,  383,  381,  381,  383,
      383,  381,  383,  381,  381,  383,  381,  383,  381,  381,
      383,  381,  383,  381,  381,  383,  381,  383,  381,  383,
      381,  383,  381,  383,  381,  383,  381,  383,  381,  381,
        0,  381,  381
    } ;

static const flex_int16_t yy_nxt[779] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,    8,    8,   24,   25,    8,    8,   26,    8,    8,
       27,   28,   28,   28,   28,   37,   28,   28,   28,   28,
       35,   28,   32,   38,   28,   31,   36,   33,   39,   40,
       73,   41,   76,   48,   47,   28,   42,   34,   28,   49,
       43,   28,   50,  136,   44,   28,   28,   28,   45,   51,
       30,   53,   55,   46,   52,   54,   56,   28,   28,   75,
       28,   28,   28,   57,   28,   34,   74,   58,   28,   28,
       61,   28,   59,   34,   60,   77,   62,   64,   28,   63,

       28,   65,   29,   28,   66,   28,   28,   79,   28,   28,
       81,   67,   83,   78,   68,   69,   82,   28,   28,   28,
       70,   86,   80,   71,   85,   84,   28,   28,   72,   87,
       97,  102,   88,   92,   89,   28,   93,   95,   28,   94,
       28,   96,  101,   28,   99,   90,   28,   28,   28,   91,
       28,   28,   98,   28,   28,   28,  107,   28,   28,  109,
      100,  110,  105,   28,  106,  108,  103,  104,  113,   28,
       28,   28,  111,  116,   28,   28,  119,   28,  112,  114,
       28,  115,  126,   28,  120,   28,  129,  118,  125,   28,
      137,  117,   28,   28,  121,  130,   28,  127,  128,  131,

       28,   28,  122,  132,   28,  133,   28,  123,  134,  139,
      124,  138,   28,  140,   28,   28,  143,   28,   28,   28,
      135,  142,   28,   28,  149,   28,   28,   28,   28,   28,
       28,  152,   28,   28,  141,   28,   28,  144,  145,  155,
      153,  127,  146,  147,  148,  154,  146,  150,  151,  156,
       79,   28,   28,   28,   28,   28,   28,   28,  159,  160,
       28,  161,  157,   28,   28,  164,  158,  162,   28,   28,
      165,  167,   28,   28,   28,  163,  174,   28,  171,  168,
      173,   28,  169,  170,  166,   28,   28,   28,  172,  175,
       28,   28,   28,  178,   28,   34,  179,   28,  182,   28,

       28,   28,   28,  176,  239,   28,  183,  177,  184,  185,
      181,  187,   28,   28,  186,  189,   28,   28,  188,  190,
      193,  191,   28,   28,   28,   28,   28,   28,  194,  192,
       28,  197,   28,   28,   28,  195,  201,   28,   28,  196,
       28,   28,  207,  206,   28,   28,  198,  109,  205,  149,
      199,  202,  203,  204,   28,  213,  212,   28,   28,  161,
       28,   28,  210,  146,   28,  200,   28,  211,  219,   28,
      218,  127,   28,   28,   28,   28,  214,  215,  216,   28,
      217,   28,   28,   28,  221,  220,  229,  223,  224,  225,
      222,  228,   28,  226,  231,   28,   28,   28,  229,   28,

       28,  230,  236,  234,   28,  237,  240,   28,  227,   28,
      242,   28,  238,  211,  232,  243,   28,   28,  235,   28,
       28,   28,   28,  241,   28,  248,  251,  252,  253,   28,
      244,  286,   28,  245,  246,  249,   28,  250,  254,   28,
       28,   28,  255,   28,   28,  256,  258,   28,  257,  247,
       55,   28,  219,   79,   28,   28,   28,  271,  280,  261,
      267,  266,  262,   28,  268,   28,   28,   28,   28,  270,
      272,  210,   28,  274,  275,  263,  211,   28,  264,  269,
       28,   28,  265,  276,   28,   28,  273,  277,  240,   28,
      283,  278,  282,   28,  287,  284,   28,   28,  289,  290,

       28,   28,   28,  291,   28,  288,  279,   28,   28,  294,
      285,  292,   28,  296,  293,   28,   28,  298,   95,   28,
       28,   28,  295,   28,   28,   28,  297,  303,   28,   54,
      305,  306,   28,  299,  302,   28,   28,   28,   28,   28,
       28,   28,   28,  309,  315,  304,  308,  310,  316,  312,
      283,  137,   28,   28,  317,   28,  313,  314,  319,   28,
      380,   28,  311,  324,   28,   28,   28,   28,   28,  322,
       28,  321,  327,  200,  202,   28,  328,   28,   28,  323,
      325,  329,   28,  332,  333,   28,   28,   28,  334,   28,
       28,   28,   28,   28,  227,  330,  337,   28,  341,  247,

      335,   28,   28,   28,   28,  342,   28,  336,   28,  339,
      269,   28,  343,   28,   28,  279,  345,  346,   28,   28,
      285,   28,  350,   28,  347,   28,   79,  351,  311,   28,
       28,  363,  358,   28,  353,  366,   28,   28,  356,  361,
       28,   28,   28,   28,  379,  377,  375,  372,  373,  371,
      374,  369,  368,  367,  365,  370,  364,  362,  360,  359,
      376,  378,  357,  355,  354,   28,  352,   28,  349,  348,
       28,   28,  344,   28,   28,   28,   28,  340,  338,   28,
       28,   28,  331,   28,  326,   28,   28,   28,   28,  320,
       28,   28,   28,   28,  318,   28,  307,   28,   28,  301,

      300,   28,   28,   28,   28,   28,   28,   28,   28,  281,
       28,   28,   28,   28,   28,   28,   28,  260,  259,   28,
       28,   28,   28,   28,   28,  233,   28,  209,  208,   28,
       28,   28,   28,   28,  180,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,  381,    3,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[779] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   10,   12,   11,   12,   15,   33,   16,   13,
       11,   26,   10,   12,   78,    9,   11,   10,   12,   13,
       26,   13,   33,   16,   15,   17,   13,   10,   14,   16,
       14,   18,   17,   78,   14,   19,   20,   32,   14,   17,
      383,   18,   20,   14,   17,   19,   20,   21,   22,   32,
       27,   35,   37,   21,   23,   22,   27,   21,   31,   39,
       23,   24,   22,   31,   22,   35,   23,   24,   36,   23,

       38,   24,  382,   42,   24,   25,   41,   37,   40,   48,
       39,   25,   41,   36,   25,   25,   40,   43,   46,   53,
       25,   43,   38,   25,   42,   41,   44,   45,   25,   43,
       48,   53,   44,   46,   45,   47,   46,   47,   49,   46,
       51,   47,   52,   52,   51,   45,   54,   55,   57,   45,
       56,   58,   49,   59,   61,   60,   57,   62,   63,   59,
       51,   60,   56,   65,   56,   58,   54,   55,   63,   64,
       67,   79,   61,   64,   66,   69,   66,   71,   62,   63,
       72,   63,   70,   70,   67,   74,   72,   65,   69,   73,
       79,   64,   68,   75,   68,   72,   76,   70,   71,   73,

       77,   80,   68,   74,   82,   75,   81,   68,   76,   81,
       68,   80,   83,   82,   85,   84,   85,   86,   91,   87,
       77,   84,   88,   89,   91,   90,   92,   93,   95,   96,
       94,   96,   97,  100,   83,   98,   99,   86,   87,  100,
       98,   95,   88,   89,   90,   99,   92,   93,   94,  101,
       97,  102,  103,  104,  106,  105,  118,  110,  103,  104,
      112,  105,  101,  107,  108,  107,  102,  105,  113,  114,
      108,  110,  115,  116,  117,  106,  118,  119,  115,  112,
      117,  121,  113,  114,  108,  122,  123,  124,  116,  119,
      125,  127,  128,  124,  129,  121,  125,  131,  128,  132,

      140,  133,  188,  122,  188,  135,  129,  123,  129,  131,
      127,  133,  134,  136,  132,  135,  138,  139,  134,  136,
      140,  138,  141,  143,  144,  145,  150,  148,  141,  139,
      153,  145,  151,  152,  155,  143,  150,  154,  159,  144,
      147,  160,  155,  154,  161,  162,  147,  148,  153,  147,
      147,  150,  151,  152,  158,  162,  159,  163,  164,  160,
      165,  166,  158,  161,  169,  147,  170,  158,  167,  167,
      166,  170,  171,  172,  173,  177,  163,  163,  164,  175,
      165,  176,  184,  174,  169,  167,  176,  172,  173,  174,
      171,  175,  178,  174,  177,  179,  183,  187,  178,  185,

      189,  176,  184,  183,  191,  185,  190,  190,  174,  192,
      191,  194,  187,  189,  179,  192,  195,  238,  183,  196,
      198,  199,  201,  190,  193,  194,  198,  199,  201,  206,
      193,  238,  203,  193,  193,  195,  204,  196,  203,  205,
      207,  210,  204,  212,  211,  205,  207,  215,  206,  193,
      211,  216,  219,  215,  217,  220,  231,  220,  231,  210,
      217,  216,  212,  213,  217,  223,  224,  225,  226,  219,
      223,  213,  234,  225,  226,  213,  213,  228,  213,  217,
      239,  230,  213,  228,  235,  236,  224,  230,  240,  252,
      235,  230,  234,  244,  239,  236,  241,  246,  241,  244,

      251,  250,  253,  246,  378,  240,  230,  254,  255,  252,
      236,  250,  256,  254,  251,  258,  261,  256,  261,  263,
      264,  265,  253,  266,  267,  268,  255,  265,  271,  263,
      267,  268,  272,  258,  264,  274,  275,  273,  277,  276,
      280,  282,  278,  273,  277,  266,  271,  273,  278,  274,
      282,  272,  284,  289,  280,  290,  275,  276,  284,  291,
      377,  292,  273,  292,  294,  295,  296,  305,  303,  290,
      304,  289,  303,  294,  295,  306,  304,  308,  309,  291,
      296,  305,  310,  308,  309,  313,  315,  316,  310,  319,
      323,  317,  321,  324,  313,  306,  317,  327,  321,  323,

      315,  330,  332,  333,  334,  324,  336,  316,  341,  319,
      330,  339,  327,  343,  345,  336,  332,  333,  350,  347,
      339,  351,  341,  353,  334,  358,  351,  343,  347,  361,
      356,  358,  353,  363,  345,  361,  366,  368,  350,  356,
      370,  372,  374,  376,  375,  373,  371,  368,  369,  367,
      370,  365,  363,  362,  360,  366,  359,  357,  355,  354,
      372,  374,  352,  349,  348,  346,  344,  342,  340,  338,
      337,  335,  331,  329,  328,  325,  322,  320,  318,  314,
      312,  311,  307,  302,  300,  299,  298,  297,  293,  288,
      287,  286,  285,  283,  281,  279,  270,  269,  262,  260,

      259,  257,  249,  248,  247,  245,  243,  242,  237,  233,
      232,  229,  227,  222,  221,  218,  214,  209,  208,  202,
      200,  197,  186,  182,  181,  180,  168,  157,  156,  149,
      146,  142,  137,  130,  126,  120,  111,  109,   50,   34,
       30,   29,   28,    8,    7,    3,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[65] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "calc-lex.l"
#line 3 "calc-lex.l"
#include <stdlib.h>
#include <stdbool.h>
#include "calc-parser.tab.h"

char* remove_plural(const char* str) {
    if (strcmp(str, "feet") == 0) {
        return strdup("foot");
    }
    if (strcmp(str, "inches") == 0) {
        return strdup("inch");
    }
    size_t len = strlen(str);
    char* copy = strdup(str);
    if (len > 1 && copy[len - 1] == 's') {
        copy[len - 1] = '\0';
    }
    return copy;
}

#line 790 "lex.yy.c"
#line 791 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 65 "calc-lex.l"


#line 1011 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 747 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "calc-lex.l"
{/*skip blanks*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "calc-lex.l"
{/*ignore*/}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "calc-lex.l"
{ yylval.value = 0; return UNIT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "calc-lex.l"
{ yylval.value = 1;  return UNIT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "calc-lex.l"
{ yylval.value = 2; return UNIT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "calc-lex.l"
{yylval.value = 3; return UNIT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "calc-lex.l"
{yylval.value = 4; return UNIT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "calc-lex.l"
{yylval.value = 5; return UNIT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "calc-lex.l"
{yylval.value = 6; return UNIT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "calc-lex.l"
{printf("seven");yylval.value = 7; return UNIT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "calc-lex.l"
{yylval.value = 8; return UNIT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "calc-lex.l"
{yylval.value = 9; return UNIT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "calc-lex.l"
{yylval.value = 10; return TEEN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "calc-lex.l"
{yylval.value = 11; return TEEN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "calc-lex.l"
{yylval.value = 12; return TEEN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "calc-lex.l"
{yylval.value = 13; return TEEN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "calc-lex.l"
{yylval.value = 14; return TEEN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "calc-lex.l"
{yylval.value = 15; return TEEN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "calc-lex.l"
{yylval.value = 16; return TEEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "calc-lex.l"
{yylval.value = 17; return TEEN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "calc-lex.l"
{yylval.value = 18; return TEEN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "calc-lex.l"
{yylval.value = 19; return TEEN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 92 "calc-lex.l"
{yylval.value = 20; return TEN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "calc-lex.l"
{yylval.value = 30; return TEN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "calc-lex.l"
{yylval.value = 40; return TEN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "calc-lex.l"
{yylval.value = 50; return TEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 96 "calc-lex.l"
{yylval.value = 60; return TEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 97 "calc-lex.l"
{yylval.value = 70; return TEN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "calc-lex.l"
{yylval.value = 80; return TEN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 99 "calc-lex.l"
{yylval.value = 90; return TEN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 101 "calc-lex.l"
{yylval.value = 100; return HUNDRED;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 102 "calc-lex.l"
{yylval.value = 1000; return HUNDRED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 103 "calc-lex.l"
{yylval.value = 1000000; return HUNDRED;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "calc-lex.l"
{yylval.value = 1000000000; return HUNDRED;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "calc-lex.l"
{ yylval.op = '+'; return PLUS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "calc-lex.l"
{ yylval.op = '-';  return MINUS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "calc-lex.l"
{ yylval.op = '*'; return TIMES; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "calc-lex.l"
{ yylval.op = '/'; return DIVIDE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "calc-lex.l"
{yylval.op = '('; return LPAREN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "calc-lex.l"
{yylval.op = ')'; return RPAREN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 114 "calc-lex.l"
{return POINT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "calc-lex.l"
{return EXP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "calc-lex.l"
{return FACT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "calc-lex.l"
{yylval.op = '-'; return NEG;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "calc-lex.l"
{return WHILE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "calc-lex.l"
{return IF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "calc-lex.l"
{return ELSE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 126 "calc-lex.l"
{yylval.value = true; return BOOLEAN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 127 "calc-lex.l"
{yylval.value = false; return BOOLEAN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "calc-lex.l"
{return INT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "calc-lex.l"
{return DOU;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 131 "calc-lex.l"
{return BOOLEAN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 132 "calc-lex.l"
{yylval.lexeme = strdup(yytext); return BOOL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 134 "calc-lex.l"
{yylval.value = '>'; return RELATION;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "calc-lex.l"
{printf("Token equals"); yylval.value = '='; return RELATION;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 136 "calc-lex.l"
{yylval.value = '<'; return RELATION;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 138 "calc-lex.l"
{yylval.measure = remove_plural(yytext); return SPACE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 139 "calc-lex.l"
{yylval.measure = remove_plural(yytext); return WEIGHT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 140 "calc-lex.l"
{yylval.measure = remove_plural(yytext); return TIME;}               
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 141 "calc-lex.l"
{yylval.measure = remove_plural(yytext); return VOLUME;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 143 "calc-lex.l"
{return RATIO;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "calc-lex.l"
{printf("Token %s",yytext);yylval.lexeme = strdup(yytext); return ID;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 147 "calc-lex.l"
{return '\n';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "calc-lex.l"
ECHO;
	YY_BREAK
#line 1399 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "calc-lex.l"

