
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[412] =
    {   0,
       66,   66,   69,   68,    1,   67,    3,   66,   66,   65,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   65,   66,   65,   66,   66,   66,    2,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   47,   66,   60,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   63,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,    5,   66,   66,   66,   66,
       66,   66,   66,   10,   66,   14,    0,   66,   66,   66,
       66,   66,    0,   62,   66,   66,    6,   66,   66,   66,
       66,   66,   66,   63,   66,   66,   66,   66,   66,   48,
       66,   66,   66,   61,   66,   66,    9,   66,    8,   66,
       66,   61,   66,   66,   66,   66,   61,   66,   66,   66,
       13,   66,    0,   66,   36,   66,   66,   66,   66,   66,
       66,   66,    0,   66,   66,   66,   66,    0,   62,   49,
       66,   66,   66,    4,   66,   66,   66,   66,   66,   66,

       66,   12,   66,   58,   66,   50,   66,   66,   27,   66,
       26,   66,   66,   66,   66,   66,   66,   66,   64,   66,
       37,   66,   66,   66,   13,    0,    0,   66,   42,   43,
       66,   11,   66,   66,   28,   66,    2,    7,   66,   66,
       38,    0,   66,   66,   66,   46,   66,   66,    0,   66,
       66,   66,   52,   66,   12,   66,   30,   15,   58,   66,
       66,   66,   66,   66,   66,   66,   61,   66,   66,   64,
       66,   66,   66,   66,   66,   66,   31,    0,    0,   66,
       66,   66,   66,   66,   66,   66,   25,   66,   43,   66,
       16,   66,   24,   35,   53,    0,   66,   66,   66,   66,

       66,   66,   19,   66,   66,   66,   57,   32,   51,   34,
       66,   66,   66,   66,    0,    0,   66,   66,   66,   29,
       20,   66,   59,   66,   66,   66,    0,   66,    0,   66,
       66,    0,   22,   66,   66,   18,    0,   66,   45,   23,
       66,    0,    0,   66,   66,   66,    0,   17,   66,   33,
        0,   66,    0,   66,   56,    0,   44,    0,   66,   56,
        0,   66,   21,   66,    0,    0,    0,   66,   39,    0,
       66,   56,    0,   66,    0,    0,    0,   66,    0,    0,
       66,    0,    0,    0,   66,    0,    0,   66,    0,   43,
        0,   66,   54,    0,   66,   55,    0,   66,   54,    0,

       66,   55,    0,   66,    0,   40,    0,   41,   40,   41,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    9,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1,    1,    1,   10,   11,   12,   13,

       14,   15,   16,   17,   18,    8,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[35] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[414] =
    {   0,
        0,    0,  432, 1218, 1218, 1218, 1218,   28,   29,   32,
       33,   36,   37,   40,   53,   72,   57,   65,   78,   58,
       90,   95,  103,  107,  116,  123,  135,   94,   61,   82,
      111,  126,  131,  139,  147,  148,  155,  156,  160,  163,
      164,  168,  167,  172,  178,  182,  192,  186,  199,  208,
      200,  212,  209,  221,  226,  232,  233,  238,  239,  242,
      243,  246,  247,  250,  257,  265,  266,  273,  276,  277,
      280,  285,  305,  290,  294,  305,  313,  317,  323,  330,
      331,  334,  337,  338,  345,  348,  352,  360,  349,  361,
      364,  369,  373,  374,  377,  380,  381,  384,  385,  389,

      397,  401,  407,  394,  412,  417,  421,  420,  424,  430,
      433,  439,  442,  447,  451,  402,  450,  455,  456,  462,
      467,  470,  476,  479,  480,  485,  417,  488,  489,  492,
      495,  499,  371,  496,  505,  509,  513,  517,  518,  521,
      526,  525,  535,  529,  538,  541,  544,  548,  549,  552,
      553,  558,  561,  562,  575,  570,  565,  576,  571,  579,
      588,  596,  595,  606,  609,  610,  614,  619,  622,  623,
      631,  635,  371,  639,  638,  646,  647,  655,  658,  661,
      110,  662,  367,  666,  669,  677,  678,  336,  681,  686,
      691,  690,  694,  695,  700,  703,  707,  713,  717,  718,

      722,  573,  726,  731,  735,  732,  738,  742,  746,  750,
      753,  756,  759,  760,  768,  769,  772,  773,  777,  798,
      781,  782,  785,  783,  799,  323,  186,  802,  806,  813,
      817,  820,  824,  825,  828,  833, 1218,  834,  832,  844,
      848,  328,  849,  852,  853,  860,  861,  865,  257,  866,
      871,  875,  872,  882,  883,  886,  890,  894,  895,  898,
      899,  902,  903,  906,  910,  915,  916,  920,  925,  930,
      931,  934,  938,  935,  941,  944,  950,  304,  319,  953,
      949,  961,  962,  965,  966,  978,  969,  977,  321,  986,
      987,  991,  995,  999, 1000,  311, 1003, 1004, 1010, 1009,

     1013, 1014, 1018, 1021, 1025, 1026, 1036, 1030, 1037, 1040,
     1043, 1044, 1047, 1050,  308,  291, 1053, 1054, 1057, 1063,
     1066, 1067, 1073, 1072, 1076, 1079,  289, 1080,  282, 1084,
     1088,  294, 1092, 1093, 1098, 1102,  286, 1105, 1106, 1110,
     1113,  276,  279, 1114, 1117, 1118,  263, 1122, 1125, 1126,
      253, 1131,  254, 1134, 1138,  203, 1142,  207, 1143,  200,
      202, 1146, 1150, 1151,  195,  182,  181, 1154, 1218,  173,
     1157, 1218,  166, 1160,  155,  166,  131, 1164,  141,  133,
     1169,  137,  116,  117, 1177,   99,  101, 1178,   87, 1218,
       92, 1181,   69,   65, 1185,   57,   53, 1186, 1218,   59,

     1189, 1218,   43, 1190,   29, 1193,   26, 1200, 1218, 1218,
     1218,   50,   46
    } ;

static const flex_int16_t yy_def[414] =
    {   0,
      411,    1,  411,  411,  411,  411,  411,  412,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,   16,  413,  413,  412,
      412,  412,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,   16,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  411,  413,  413,  413,
      413,  413,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  411,  413,  413,  413,  413,  413,  413,  413,
      155,  413,  411,  413,  413,  413,  413,  411,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  155,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  155,  413,  411,  411,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  411,  413,  155,  413,
      413,  411,  413,  413,  413,  413,  413,  413,  411,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  411,  411,  413,
      155,  413,  413,  413,  413,  413,  413,  413,  411,  413,
      413,  413,  413,  413,  413,  411,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  411,  411,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  411,  413,  411,  413,
      413,  411,  413,  413,  413,  413,  411,  413,  413,  413,
      413,  411,  411,  413,  413,  413,  411,  413,  413,  413,
      411,  413,  411,  413,  413,  411,  413,  411,  413,  411,
      411,  413,  413,  413,  411,  411,  411,  413,  411,  411,
      413,  411,  411,  413,  411,  411,  411,  413,  411,  411,
      413,  411,  411,  411,  413,  411,  411,  413,  411,  411,
      411,  413,  411,  411,  413,  411,  411,  413,  411,  411,

      413,  411,  411,  413,  411,  413,  411,  413,  411,  411,
        0,  411,  411
    } ;

static const flex_int16_t yy_nxt[1253] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,    9,    9,   26,   27,    9,    9,
       28,    9,    9,   29,   30,   30,   32,   34,   30,   30,
       34,   34,   30,   30,   34,   34,   30,   33,   34,   41,
       39,   31,  410,   36,   35,  409,   40,   42,   37,   30,
      407,   34,   43,   30,   30,   34,   34,   30,   38,   34,
       44,   30,   45,   34,   79,   58,  405,   46,   30,  403,
       34,   47,   52,  402,   30,   48,   34,   53,   30,   49,
       32,  400,   55,   54,   50,  399,   30,   51,   34,   56,

       30,   30,   34,   34,   57,  397,  396,   59,   60,   30,
       78,   34,   61,   30,  394,   34,   62,   30,  393,   32,
       63,   38,   30,  233,   34,   64,   33,  234,   65,   30,
       66,   34,   30,  391,   32,   67,   69,   30,   68,   34,
       70,  390,  235,   71,   33,   30,  389,   34,   72,  387,
      386,   73,   74,   30,   30,   34,   34,   75,  384,   38,
       76,   30,   30,   34,   34,   77,   30,   80,   34,   30,
       30,   34,   34,   30,   30,   34,   34,   81,   30,  383,
       34,   82,   85,  382,   30,   83,   34,   88,   30,  227,
       34,   89,   30,  380,   34,   87,   84,   86,   30,   94,

       34,  379,  377,   92,   90,   30,   30,   34,   34,  279,
       91,   93,  376,   95,   30,   30,   34,   34,   30,  375,
       34,  102,  101,  373,   96,  103,  372,   30,   97,   34,
       98,  370,   30,   99,   34,  369,  100,  104,   30,   30,
       34,   34,  105,  106,   30,   30,   34,   34,   30,   30,
       34,   34,   30,   30,   34,   34,   30,  108,   34,  107,
      249,  113,  111,   30,  112,   34,  109,  367,  114,  110,
      116,   30,   30,   34,   34,  366,  365,  115,  117,   30,
      296,   34,   30,   30,   34,   34,   30,  122,   34,  125,
      119,   30,  361,   34,  118,  360,   30,  133,   34,  358,

       30,  120,   34,  121,  356,  123,  126,  353,  124,  127,
      132,   30,  351,   34,  128,  134,  343,  342,   33,   30,
      329,   34,  129,   30,  327,   34,  136,  130,  316,   30,
      131,   34,  315,  135,  138,  137,   30,   30,   34,   34,
       30,  289,   34,   30,   30,   34,   34,  278,  139,  140,
      141,   30,  242,   34,   30,   30,   34,   34,   30,  145,
       34,  142,  147,  143,  144,  146,   30,   30,   34,   34,
       30,  237,   34,  151,  150,   30,  148,   34,  149,   30,
       30,   34,   34,   30,  226,   34,   30,   30,   34,   34,
       30,   30,   34,   34,  157,   30,  152,   34,  188,  153,

       30,  154,   34,   30,  155,   34,  156,   30,   30,   34,
       34,  154,  158,   30,  159,   34,  160,   38,   30,   84,
       34,  134,  183,   30,  161,   34,   30,   30,   34,   34,
       30,  411,   34,  162,  163,  411,   30,  165,   34,   30,
      411,   34,  164,  166,  411,   30,  167,   34,   30,  411,
       34,  170,  168,   30,  173,   34,   30,   30,   34,   34,
      171,   30,   30,   34,   34,  411,  411,  169,   30,  411,
       34,  174,  411,   30,  172,   34,   30,  176,   34,  411,
      178,  175,   30,  177,   34,   30,   30,   34,   34,  180,
      411,   30,  179,   34,   30,   30,   34,   34,   30,  182,

       34,   30,   30,   34,   34,   30,  181,   34,  186,   38,
      411,   30,  187,   34,  184,   30,  411,   34,  190,   30,
      185,   34,  189,   30,   30,   34,   34,   30,  191,   34,
      192,   30,   30,   34,   34,   30,  193,   34,  195,  196,
      194,   30,  197,   34,   30,  411,   34,   30,  198,   34,
       30,  199,   34,  200,   30,   30,   34,   34,   30,   30,
       34,   34,  203,  201,   30,  411,   34,   30,   30,   34,
       34,   30,  204,   34,  206,  202,   30,   30,   34,   34,
      205,   30,   30,   34,   34,   30,  254,   34,  207,  255,
      256,  157,  208,  210,   30,  411,   34,  116,  212,  411,

      411,   30,   30,   34,   34,  257,  213,  209,  211,  215,
      216,  411,   30,  214,   34,   30,   30,   34,   34,  411,
       30,  217,   34,  411,  411,   30,  218,   34,   30,   30,
       34,   34,  411,  411,  219,  167,  220,   30,  411,   34,
      154,   30,  227,   34,   30,   30,   34,   34,  221,  222,
      223,  225,   30,   30,   34,   34,  411,  411,  224,  134,
      411,   30,  228,   34,   30,  411,   34,   30,   30,   34,
       34,  411,   30,  229,   34,   30,  411,   34,  238,  231,
      230,  236,  232,   30,   30,   34,   34,   30,  411,   34,
      238,  411,   30,  239,   34,  240,   30,   30,   34,   34,

       30,   30,   34,   34,  241,  243,   30,  246,   34,   30,
      411,   34,  248,   30,  411,   34,  249,  245,  411,   30,
      244,   34,  247,   30,   30,   34,   34,  218,   30,  411,
       34,  252,   30,  411,   34,  253,  250,   30,   30,   34,
       34,   30,  251,   34,   30,  411,   34,  258,   30,  411,
       34,  261,   30,  411,   34,  262,   30,  259,   34,   30,
      260,   34,   30,  263,   34,   30,   30,   34,   34,  264,
      411,  411,  265,  266,   30,   30,   34,   34,   30,   30,
       34,   34,  268,   30,  411,   34,   60,   30,   30,   34,
       34,   30,  411,   34,  267,   84,  275,  269,  411,   33,

      276,  411,  274,  270,   30,   30,   34,   34,   30,  411,
       34,  280,   30,  217,   34,  277,  411,  271,  218,   30,
      272,   34,  411,   30,  273,   34,   30,  411,   34,   84,
       30,   30,   34,   34,   30,  411,   34,  282,  283,   30,
       30,   34,   34,  411,  411,  285,  284,  281,   33,  286,
       30,  411,   34,  288,   30,   30,   34,   34,   30,   30,
       34,   34,  411,  411,  287,  291,   30,   30,   34,   34,
      292,   30,   30,   34,   34,  297,  290,   30,   30,   34,
       34,   30,  294,   34,  298,  293,  295,  299,   30,   30,
       34,   34,   30,  411,   34,  300,   30,  411,   34,  301,

       30,   30,   34,   34,   30,   30,   34,   34,   30,   30,
       34,   34,   30,  411,   34,  302,   30,  411,   34,  306,
      303,   30,   30,   34,   34,  411,   30,  308,   34,  304,
      305,   30,  411,   34,  102,  307,   30,   30,   34,   34,
       30,   30,   34,   34,   30,  309,   34,   30,   59,   34,
       30,  311,   34,  411,  313,  310,   30,  314,   34,   30,
      411,   34,  318,  411,  312,   33,  319,   30,   30,   34,
       34,   30,   30,   34,   34,   30,  411,   34,  317,  324,
      411,  320,  321,   30,   30,   34,   34,  411,  411,  322,
      323,  325,   30,   30,   34,   34,  411,   30,  326,   34,

      411,   30,  291,   34,  328,   30,   30,   34,   34,   30,
       30,   34,   34,  332,  411,   30,   30,   34,   34,   30,
       30,   34,   34,  335,   30,  331,   34,   30,  330,   34,
      333,   30,   30,   34,   34,  411,   30,  209,   34,  337,
      334,  211,   30,   30,   34,   34,   30,  336,   34,   30,
       30,   34,   34,   30,  338,   34,   30,  339,   34,   30,
       30,   34,   34,   30,  411,   34,  344,  345,  340,   30,
      346,   34,   30,   30,   34,   34,  347,  341,   30,   30,
       34,   34,   30,  235,   34,   30,   30,   34,   34,  411,
       30,  350,   34,  348,   30,  411,   34,  354,   30,   30,

       34,   34,  411,  349,   30,  411,   34,  352,   30,  257,
       34,   30,   30,   34,   34,  355,   30,  357,   34,   30,
       30,   34,   34,   30,   30,   34,   34,  359,   30,  277,
       34,   30,   30,   34,   34,  362,  411,   30,  363,   34,
       30,  287,   34,  411,   30,  364,   34,  293,   30,   30,
       34,   34,   30,  411,   34,  368,   30,   30,   34,   34,
       30,  411,   34,   30,  371,   34,   30,  320,   34,   84,
       30,  411,   34,  374,  411,   30,  381,   34,  411,  411,
      385,  378,  388,   30,   30,   34,   34,   30,  411,   34,
      392,   30,   30,   34,   34,   30,   30,   34,   34,   30,

      411,   34,  401,  404,  395,  411,   30,  398,   34,  411,
      411,  411,  411,  411,  411,  406,  408,    3,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411
    } ;

static const flex_int16_t yy_chk[1253] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,    8,    9,   10,   11,
       10,   11,   12,   13,   12,   13,   14,  413,   14,   14,
       13,  412,  407,   12,   11,  405,   13,   14,   12,   15,
      403,   15,   14,   17,   20,   17,   20,   29,   12,   29,
       15,   18,   15,   18,   29,   20,  400,   15,   16,  397,
       16,   16,   17,  396,   19,   16,   19,   18,   30,   16,
       30,  394,   19,   18,   16,  393,   21,   16,   21,   19,

       28,   22,   28,   22,   19,  391,  389,   21,   22,   23,
       28,   23,   22,   24,  387,   24,   23,   31,  386,   31,
       23,   24,   25,  181,   25,   23,  181,  181,   24,   26,
       24,   26,   32,  384,   32,   25,   26,   33,   25,   33,
       26,  383,  181,   26,   27,   34,  382,   34,   27,  380,
      379,   27,   27,   35,   36,   35,   36,   27,  377,   35,
       27,   37,   38,   37,   38,   27,   39,   36,   39,   40,
       41,   40,   41,   43,   42,   43,   42,   37,   44,  376,
       44,   39,   42,  375,   45,   40,   45,   44,   46,  227,
       46,   45,   48,  373,   48,   43,   41,   42,   47,   48,

       47,  370,  367,   47,   45,   49,   51,   49,   51,  227,
       46,   47,  366,   49,   50,   53,   50,   53,   52,  365,
       52,   52,   51,  361,   49,   52,  360,   54,   49,   54,
       50,  358,   55,   50,   55,  356,   50,   53,   56,   57,
       56,   57,   54,   56,   58,   59,   58,   59,   60,   61,
       60,   61,   62,   63,   62,   63,   64,   58,   64,   56,
      249,   62,   61,   65,   61,   65,   59,  353,   63,   60,
       65,   66,   67,   66,   67,  351,  347,   64,   66,   68,
      249,   68,   69,   70,   69,   70,   71,   69,   71,   71,
       68,   72,  343,   72,   67,  342,   74,   75,   74,  337,

       75,   68,   75,   68,  332,   69,   72,  329,   70,   73,
       74,   76,  327,   76,   73,   75,  316,  315,   73,   77,
      296,   77,   73,   78,  289,   78,   77,   73,  279,   79,
       73,   79,  278,   76,   78,   77,   80,   81,   80,   81,
       82,  242,   82,   83,   84,   83,   84,  226,   79,   80,
       81,   85,  188,   85,   86,   89,   86,   89,   87,   85,
       87,   82,   87,   83,   84,   86,   88,   90,   88,   90,
       91,  183,   91,   91,   90,   92,   88,   92,   89,   93,
       94,   93,   94,   95,  173,   95,   96,   97,   96,   97,
       98,   99,   98,   99,   97,  100,   92,  100,  133,   93,

      104,   94,  104,  101,   95,  101,   96,  102,  116,  102,
      116,   98,   99,  103,  100,  103,  103,  101,  105,  104,
      105,  102,  127,  106,  105,  106,  108,  107,  108,  107,
      109,    3,  109,  106,  107,    0,  110,  109,  110,  111,
        0,  111,  108,  110,    0,  112,  111,  112,  113,    0,
      113,  113,  111,  114,  115,  114,  117,  115,  117,  115,
      114,  118,  119,  118,  119,    0,    0,  112,  120,    0,
      120,  117,    0,  121,  114,  121,  122,  119,  122,    0,
      121,  118,  123,  120,  123,  124,  125,  124,  125,  123,
        0,  126,  122,  126,  128,  129,  128,  129,  130,  125,

      130,  131,  134,  131,  134,  132,  124,  132,  131,  128,
        0,  135,  132,  135,  129,  136,    0,  136,  135,  137,
      130,  137,  134,  138,  139,  138,  139,  140,  136,  140,
      136,  142,  141,  142,  141,  144,  138,  144,  140,  141,
      139,  143,  142,  143,  145,    0,  145,  146,  143,  146,
      147,  145,  147,  146,  148,  149,  148,  149,  150,  151,
      150,  151,  149,  147,  152,    0,  152,  153,  154,  153,
      154,  157,  151,  157,  153,  148,  156,  159,  156,  159,
      152,  155,  158,  155,  158,  160,  202,  160,  155,  202,
      202,  155,  155,  158,  161,    0,  161,  156,  159,    0,

        0,  163,  162,  163,  162,  202,  160,  155,  158,  162,
      163,    0,  164,  161,  164,  165,  166,  165,  166,    0,
      167,  164,  167,    0,    0,  168,  164,  168,  169,  170,
      169,  170,    0,    0,  165,  166,  168,  171,    0,  171,
      167,  172,  174,  172,  175,  174,  175,  174,  169,  169,
      170,  172,  176,  177,  176,  177,    0,    0,  171,  177,
        0,  178,  174,  178,  179,    0,  179,  180,  182,  180,
      182,    0,  184,  176,  184,  185,    0,  185,  184,  179,
      178,  182,  180,  186,  187,  186,  187,  189,    0,  189,
      186,    0,  190,  184,  190,  185,  192,  191,  192,  191,

      193,  194,  193,  194,  187,  191,  195,  193,  195,  196,
        0,  196,  196,  197,    0,  197,  198,  192,    0,  198,
      191,  198,  195,  199,  200,  199,  200,  197,  201,    0,
      201,  200,  203,    0,  203,  201,  198,  204,  206,  204,
      206,  205,  199,  205,  207,    0,  207,  203,  208,    0,
      208,  207,  209,    0,  209,  208,  210,  204,  210,  211,
      205,  211,  212,  210,  212,  213,  214,  213,  214,  212,
        0,    0,  213,  214,  215,  216,  215,  216,  217,  218,
      217,  218,  216,  219,    0,  219,  218,  221,  222,  221,
      222,  223,    0,  223,  215,  222,  224,  217,    0,  224,

      224,    0,  223,  219,  220,  225,  220,  225,  228,    0,
      228,  228,  229,  220,  229,  224,    0,  220,  220,  230,
      220,  230,    0,  231,  220,  231,  232,    0,  232,  231,
      233,  234,  233,  234,  235,    0,  235,  233,  234,  236,
      238,  236,  238,    0,    0,  239,  236,  232,  239,  239,
      240,    0,  240,  240,  241,  243,  241,  243,  244,  245,
      244,  245,    0,    0,  239,  244,  246,  247,  246,  247,
      245,  248,  250,  248,  250,  250,  243,  251,  253,  251,
      253,  252,  247,  252,  251,  245,  248,  252,  254,  255,
      254,  255,  256,    0,  256,  254,  257,    0,  257,  256,

      258,  259,  258,  259,  260,  261,  260,  261,  262,  263,
      262,  263,  264,    0,  264,  260,  265,    0,  265,  264,
      261,  266,  267,  266,  267,    0,  268,  266,  268,  262,
      263,  269,    0,  269,  269,  265,  270,  271,  270,  271,
      272,  274,  272,  274,  273,  268,  273,  275,  271,  275,
      276,  273,  276,    0,  275,  272,  277,  276,  277,  280,
        0,  280,  281,    0,  274,  281,  281,  282,  283,  282,
      283,  284,  285,  284,  285,  287,    0,  287,  280,  285,
        0,  281,  282,  288,  286,  288,  286,    0,    0,  283,
      284,  286,  290,  291,  290,  291,    0,  292,  288,  292,

        0,  293,  290,  293,  292,  294,  295,  294,  295,  297,
      298,  297,  298,  299,    0,  300,  299,  300,  299,  301,
      302,  301,  302,  302,  303,  298,  303,  304,  297,  304,
      300,  305,  306,  305,  306,    0,  308,  304,  308,  307,
      301,  305,  307,  309,  307,  309,  310,  306,  310,  311,
      312,  311,  312,  313,  311,  313,  314,  312,  314,  317,
      318,  317,  318,  319,    0,  319,  317,  318,  313,  320,
      319,  320,  321,  322,  321,  322,  323,  314,  324,  323,
      324,  323,  325,  322,  325,  326,  328,  326,  328,    0,
      330,  326,  330,  324,  331,    0,  331,  330,  333,  334,

      333,  334,    0,  325,  335,    0,  335,  328,  336,  334,
      336,  338,  339,  338,  339,  331,  340,  335,  340,  341,
      344,  341,  344,  345,  346,  345,  346,  338,  348,  341,
      348,  349,  350,  349,  350,  344,    0,  352,  345,  352,
      354,  349,  354,    0,  355,  346,  355,  352,  357,  359,
      357,  359,  362,    0,  362,  354,  363,  364,  363,  364,
      368,    0,  368,  371,  359,  371,  374,  364,  374,  371,
      378,    0,  378,  362,    0,  381,  374,  381,    0,    0,
      378,  368,  381,  385,  388,  385,  388,  392,    0,  392,
      385,  395,  398,  395,  398,  401,  404,  401,  404,  406,

        0,  406,  395,  398,  388,    0,  408,  392,  408,    0,
        0,    0,    0,    0,    0,  401,  404,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[69] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "calc-lex.l"
#line 3 "calc-lex.l"
#include <stdlib.h>
#include <stdbool.h>
#include "calc-parser.tab.h"

char* remove_plural(const char* str) {
    if (strcmp(str, "feet") == 0) {
        return strdup("foot");
    }
    if (strcmp(str, "inches") == 0) {
        return strdup("inch");
    }
    size_t len = strlen(str);
    char* copy = strdup(str);
    if (len > 1 && copy[len - 1] == 's') {
        copy[len - 1] = '\0';
    }
    return copy;
}

#line 908 "lex.yy.c"
#line 909 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 63 "calc-lex.l"


#line 1129 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 412 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1218 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "calc-lex.l"
{/*skip blanks*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "calc-lex.l"
{/*ignore*/}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "calc-lex.l"
{/*ignore*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "calc-lex.l"
{yylval.value = 0; return UNIT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 70 "calc-lex.l"
{yylval.value = 1; return UNIT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 71 "calc-lex.l"
{yylval.value = 2; return UNIT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 72 "calc-lex.l"
{yylval.value = 3; return UNIT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "calc-lex.l"
{yylval.value = 4; return UNIT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "calc-lex.l"
{yylval.value = 5; return UNIT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 75 "calc-lex.l"
{yylval.value = 6; return UNIT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 76 "calc-lex.l"
{yylval.value = 7; return UNIT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "calc-lex.l"
{yylval.value = 8; return UNIT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 78 "calc-lex.l"
{yylval.value = 9; return UNIT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "calc-lex.l"
{yylval.value = 10; return TEEN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "calc-lex.l"
{yylval.value = 11; return TEEN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "calc-lex.l"
{yylval.value = 12; return TEEN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "calc-lex.l"
{yylval.value = 13; return TEEN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "calc-lex.l"
{yylval.value = 14; return TEEN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "calc-lex.l"
{yylval.value = 15; return TEEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "calc-lex.l"
{yylval.value = 16; return TEEN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "calc-lex.l"
{yylval.value = 17; return TEEN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "calc-lex.l"
{yylval.value = 18; return TEEN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 89 "calc-lex.l"
{yylval.value = 19; return TEEN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 91 "calc-lex.l"
{yylval.value = 20; return TEN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 92 "calc-lex.l"
{yylval.value = 30; return TEN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 93 "calc-lex.l"
{yylval.value = 40; return TEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "calc-lex.l"
{yylval.value = 50; return TEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "calc-lex.l"
{yylval.value = 60; return TEN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 96 "calc-lex.l"
{yylval.value = 70; return TEN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 97 "calc-lex.l"
{yylval.value = 80; return TEN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 98 "calc-lex.l"
{yylval.value = 90; return TEN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "calc-lex.l"
{yylval.value = 100; return HUNDRED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "calc-lex.l"
{yylval.value = 1000; return HUNDRED;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "calc-lex.l"
{yylval.value = 1000000; return HUNDRED;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "calc-lex.l"
{yylval.value = 1000000000; return HUNDRED;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "calc-lex.l"
{ yylval.op = '+'; return PLUS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "calc-lex.l"
{ yylval.op = '-';  return MINUS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "calc-lex.l"
{ yylval.op = '*'; return TIMES; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "calc-lex.l"
{ yylval.op = '/'; return DIVIDE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "calc-lex.l"
{yylval.op = '('; return LPAREN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "calc-lex.l"
{yylval.op = ')'; return RPAREN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "calc-lex.l"
{return POINT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "calc-lex.l"
{return EXP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "calc-lex.l"
{return FACT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "calc-lex.l"
{yylval.op = '-'; return NEG;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "calc-lex.l"
{return WHILE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "calc-lex.l"
{return IF;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 123 "calc-lex.l"
{return ELSE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 125 "calc-lex.l"
{yylval.value = true; return BOOLEAN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 126 "calc-lex.l"
{yylval.value = false; return BOOLEAN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "calc-lex.l"
{return INT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "calc-lex.l"
{return DOU;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "calc-lex.l"
{return BOOL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "calc-lex.l"
{yylval.lexeme = strdup(">="); return RELATION;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "calc-lex.l"
{yylval.lexeme = strdup("<="); return RELATION;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "calc-lex.l"
{yylval.lexeme = strdup("!="); return RELATION;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "calc-lex.l"
{yylval.lexeme = strdup(">"); return RELATION;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "calc-lex.l"
{yylval.lexeme = strdup("="); return RELATION;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "calc-lex.l"
{yylval.lexeme = strdup("<"); return RELATION;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "calc-lex.l"
{return ASSIGN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 141 "calc-lex.l"
{
    yylval.quantity.unit = remove_plural(yytext);
    yylval.quantity.type = strdup("SPACE");
    yylval.quantity.value = 1;
    yylval.quantity.dimension = 1;
    return MEASURE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 149 "calc-lex.l"
{
    yylval.quantity.unit = remove_plural(yytext);
    yylval.quantity.type = strdup("WEIGHT");
    yylval.quantity.value = 1;
    yylval.quantity.dimension = 1;
    return MEASURE;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 157 "calc-lex.l"
{
    yylval.quantity.unit = remove_plural(yytext);
    yylval.quantity.type = strdup("TIME");
    yylval.quantity.value = 1;
    yylval.quantity.dimension = 1;
    return MEASURE;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "calc-lex.l"
{
    yylval.quantity.unit = remove_plural(yytext);
    yylval.quantity.type = strdup("VOLUME");
    yylval.quantity.value = 1;
    yylval.quantity.dimension = 1;
    return MEASURE;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "calc-lex.l"
{yylval.lexeme = strdup(yytext); return BOOL_ID;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 174 "calc-lex.l"
{yylval.lexeme = strdup(yytext); return ID;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 176 "calc-lex.l"
{return '\n';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 178 "calc-lex.l"
ECHO;
	YY_BREAK
#line 1561 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 412 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 412 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 411);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "calc-lex.l"


